### ISSUE TITLE
TMB code wrong when only one smoother

### ISSUE THREAD

**Issue by markbravington** [dill/mgcvminusminus#4]
If you've just got a single lambda, then log_lambda gets declared as a PARAMETER not a PARAMETER_VECTOR, and lambda ditto, but the code for K_defs still refers to lambda(0), which leads to a compile error.

Perhaps the cleanest is to change the sp_scale_defs bit by removing the 'if( n.sp==1) {}' bit and just always declaring log_lambda and lambda as vectors. NFI if that would have Side Effects though...

Here's the R code for a 2D smooth that showed the bug. You should be able to see the error in the file 'thingo.cpp' at lines 27/28 (on my system), which read

  // define the real penalties
  Eigen::SparseMatrix<Type> K1 = lambda(0)*S1;

and you can see that it should just be lambda not lambda(0)
  tmb <- TMBam(y ~ s(x, z), family = poisson(link = log), data = testdf, file = "thingo")

**Comment by dill** [comment]
Thanks Mark. Yes, I think it was a mistake to separate-out the case `length(sp)=1` and `length(sp)>1` cases. I don't think there's any penalty (pun intended) to declaring this as `PARAMETER_VECTOR` for the whole thing. I'll go with that as a fix as it simplifies the code.
